name: tools
description: A collection of command-line tools for developing the dough interpreter.
publish_to: none

environment:
  sdk: ^3.8.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
